CREATE TABLE "VRMDM_CONTROL"."ODI_AUTO__SRC2STG" (
    MAPPING_NAME VARCHAR(250) NOT NULL,
    SOURCE_MODEL VARCHAR(250) NOT NULL,
    SOURCE_TABLE VARCHAR(250) NOT NULL,
    TARGET_MODEL VARCHAR(250) NOT NULL,
    TARGET_TABLE VARCHAR(250) NOT NULL,
    ACTIVE_YN VARCHAR(1) NOT NULL,
    DELETE_IF_EXSTS_YN VARCHAR(1) NOT NULL
);

