TRUNCATE TABLE "VRMDM_CONTROL"."ODI_AUTO__SRC2STG";

INSERT INTO "VRMDM_CONTROL"."ODI_AUTO__SRC2STG" (MAPPING_NAME, SOURCE_MODEL, SOURCE_TABLE, TARGET_MODEL, TARGET_TABLE, ACTIVE_YN, DELETE_IF_EXSTS_YN) VALUES ('S2S_PG_VEHICLE_SERVICE','PG_VRM_VEHICLE_SERVICE','vehicle_aud','ORA_VRM_STAGE','STG_VEHICLE_AUD','Y','Y');
